apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

resources:
  - ../../base
  - namespace.yaml
  # - ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

commonLabels:
  environment: dev

commonAnnotations:
  environment: development
  managed-by: argocd

images:
  - name: uhub.service.ucloud.cn/base-images/wudi-app
    newTag: dev-latest

replicas:
  - name: myapp
    count: 1
