apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-project
  namespace: argocd
  labels:
    project: myapp
spec:
  description: "MyApp GitOps Project"
  sourceRepos:
    - 'https://github.com/xinxin20020807/gitops.git'
  destinations:
    - namespace: 'myapp-dev'
      server: https://kubernetes.default.svc
    - namespace: 'myapp-prod'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: ReplicaSet
    - group: 'extensions'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
  roles:
    - name: developer
      description: "Developer role for dev environment"
      policies:
        - p, proj:myapp-project:developer, applications, get, myapp-project/myapp-dev, allow
        - p, proj:myapp-project:developer, applications, sync, myapp-project/myapp-dev, allow
        - p, proj:myapp-project:developer, applications, action/*, myapp-project/myapp-dev, allow
      groups:
        - myapp-developers
    - name: operator
      description: "Operator role for prod environment"
      policies:
        - p, proj:myapp-project:operator, applications, get, myapp-project/*, allow
        - p, proj:myapp-project:operator, applications, sync, myapp-project/*, allow
        - p, proj:myapp-project:operator, applications, action/*, myapp-project/*, allow
        - p, proj:myapp-project:operator, applications, delete, myapp-project/*, deny
      groups:
        - myapp-operators
  syncWindows:
    - kind: allow
      schedule: '* * * * *'  # Allow sync during business hours on weekdays
      duration: 8h
      applications:
        - myapp-dev
    - kind: deny
      schedule: '0 18-8 * * *'  # Deny sync during off-hours for prod
      duration: 14h
      applications:
        - myapp-prod
      manualSync: true  # Allow manual sync even during deny window
