apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-prod

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
  - service-patch.yaml

commonLabels:
  environment: prod

commonAnnotations:
  environment: production

images:
  - name: uhub.service.ucloud.cn/base-images/wudi-app
    newTag: v1.0.0

replicas:
  - name: myapp
    count: 3
