apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myapp-pdb
  labels:
    app: myapp
    environment: prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: myapp
      environment: prod