apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  labels:
    app: myapp
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  database-username: bXlhcHA=  # myapp
  database-password: cGFzc3dvcmQ=  # password
  api-key: YWJjZGVmZ2hpams=  # abcdefghijk
  jwt-secret: c3VwZXJzZWNyZXRrZXk=  # supersecretkey